version = "3.6.0"
runner.dialect = scala213
align.preset = none
align.openParenCallSite = false
align.arrowEnumeratorGenerator = true
align.tokens = [
  {
    code = "=>"
    owners = [{
      regex = "Case"
    }]
  },
  {
    code = "="
    owners = []
  },
  {
    code = "%"
    owners = [{
      regex = "Term.ApplyInfix"
    }]
  },
  {
    code = "%%"
    owners = [{
      regex = "Term.ApplyInfix"
    }]
  }
]
maxColumn = 140
docstrings.style = Asterisk
docstrings.wrap = yes
docstrings.wrapMaxColumn = 100
optIn.breakChainOnFirstMethodDot = true
spaces.afterKeywordBeforeParen = true
indent.callSite = 2
indent.defnSite = 2
verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 3
verticalMultiline.newlineAfterOpenParen = true
danglingParentheses.defnSite = true
danglingParentheses.exclude = []
importSelectors = noBinPack
rewrite.rules = [
  Imports,
  RedundantBraces,
  RedundantParens,
  PreferCurlyFors
]
rewrite.imports.sort = ascii