# Copyright (c) 2014-present Snowplow Analytics Ltd. All rights reserved.
#
# This software is made available by Snowplow Analytics, Ltd.,
# under the terms of the Snowplow Limited Use License Agreement, Version 1.1
# located at https://docs.snowplow.io/limited-use-license-1.1
# BY INSTALLING, DOWNLOADING, ACCESSING, USING OR DISTRIBUTING ANY PORTION
# OF THE SOFTWARE, YOU AGREE TO THE TERMS OF SUCH LICENSE AGREEMENT.

{
  "input": ${snowplow.defaults.sources.kinesis}
  "input": {
    "appName": "snowplow-s3-loader"
    "kinesis": {
      "appName": ${input.appName}
    }
  }
  "output": {
    "bad": ${snowplow.defaults.sinks.kinesis}
  }
  "monitoring": {
    "metrics": {
      "statsd": {
        "prefix": "snowplow.s3loader"
      }
    }
  }
}
