addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("com.snowplowanalytics"     % "sbt-snowplow-release" % "0.4.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.11.0")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.1.1")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"           % "5.10.0")
