# Copyright (c) 2014-present Snowplow Analytics Ltd. All rights reserved.
#
# This software is made available by Snowplow Analytics, Ltd.,
# under the terms of the Snowplow Limited Use License Agreement, Version 1.1
# located at https://docs.snowplow.io/limited-use-license-1.1
# BY INSTALLING, DOWNLOADING, ACCESSING, USING OR DISTRIBUTING ANY PORTION
# OF THE SOFTWARE, YOU AGREE TO THE TERMS OF SUCH LICENSE AGREEMENT.

{
  "license" {
    "accept": "false"
    "accept": ${?ACCEPT_LIMITED_USE_LICENSE}
  }
  "output": {
    "good": {
      "compressionType": "gzip"
    }
  }
  "streams": {}
  "batching": {
    "maxBytes": 67108864
    "maxDelay": "2 minutes"
  }
  "cpuParallelismFactor": 1
  "uploadParallelismFactor": 2
  "decompression": {
    "maxBytesInBatch": 5242880
    "maxBytesSinglePayload": 10000000
  }
  "monitoring": {
    "metrics": {
      "statsd": ${snowplow.defaults.statsd}
      "statsd": {
        "prefix": "snowplow.blob.loader.aws"
      }
      "prometheus": ${snowplow.defaults.prometheus}
    }
    "sentry": ${snowplow.defaults.sentry}
    "healthProbe": {
      "port": 8000
      "unhealthyLatency": "2 minutes"
    }
  }
}